apiVersion: batch/v1
kind: CronJob
metadata:
  name: iam-init
spec:
  schedule: "{{ .Values.cron }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: iam-init
              image: {{ tpl .Values.iam_initializer_image_location . }}
              imagePullPolicy: Always
              env:
                - name: ENVIRONMENT.STRICT
                  value: {{ .Values.environment.strict | quote }}
                - name: ENVIRONMENT.TYPE
                  valueFrom:
                    configMapKeyRef:
                      name: securebanking-platform-config
                      key: ENVIRONMENT_TYPE
                - name: IDENTITY_PLATFORM_FQDN # variable to run the command shell, the shell doesn't support variables with dot.
                  valueFrom:
                    configMapKeyRef:
                      name: securebanking-platform-config
                      key: IDENTITY_PLATFORM_FQDN
                - name: HOSTS.IDENTITY_PLATFORM_FQDN
                  valueFrom:
                    configMapKeyRef:
                      name: securebanking-platform-config
                      key: IDENTITY_PLATFORM_FQDN
                - name: HOSTS.RCS_UI_FQDN
                  valueFrom:
                    configMapKeyRef:
                      name: securebanking-platform-config
                      key: RCS_UI_FQDN
                {{- if eq .Values.environment.fr_platform.type "FIDC" }}
                - name: USERS.FR_PLATFORM_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: initializer-secret
                      key: fr-platform-admin-password
                - name: USERS.FR_PLATFORM_ADMIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: initializer-secret
                      key: fr-platform-admin-user
                {{- else }}
                - name: USERS.FR_PLATFORM_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: am-env-secrets
                      key: AM_PASSWORDS_AMADMIN_CLEAR       
                {{ end }}                
              command: [ "/bin/sh", "-c" ]
              args:
                - |
                  echo "IDENTITY_PLATFORM_FQDN $IDENTITY_PLATFORM_FQDN"
                  until $(curl -X GET --output /dev/null --silent --head --fail -H "X-OpenIDM-Username: anonymous" \
                  -H "X-OpenIDM-Password: anonymous" -H "X-OpenIDM-NoSession: true" \
                  https://$IDENTITY_PLATFORM_FQDN/openidm/info/ping)
                  do
                  echo "IDM not ready"
                  sleep 10
                  done
                  ./initialize
          restartPolicy: OnFailure
